# Generated by Django 5.2.4 on 2025-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
